"""Write a human-readable PR description from the ticket and the actual diff."""
import logging
import re

from app.jira_client import JiraIssue

log = logging.getLogger(__name__)

MAX_DIFF_CHARS = 12_000

PROMPT = """You are writing the description of a GitHub pull request that fixes a Jira ticket.

Jira ticket {key}: {summary}
Ticket description:
{description}

The diff of the pull request:
```diff
{diff}
```

Write the PR description in GitHub Markdown with exactly these sections:

## Summary
One or two sentences: what problem the ticket describes and how this PR fixes it.

## Changes
One bullet per meaningful change, naming the file in backticks and saying what changed and why.
Describe only what the diff actually does. Do not invent changes, tests or files.

## How to verify
2-4 short, concrete steps a reviewer can follow to check the fix.

Output only the Markdown, no preamble and no code fence around it."""


def _complete(model: str, prompt: str) -> tuple[str, dict[str, int]]:
    # litellm is installed with Aider and understands the same model names (e.g. groq/...).
    from litellm import completion

    resp = completion(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        timeout=90,
    )
    u = getattr(resp, "usage", None)
    usage = {"sent": getattr(u, "prompt_tokens", 0) or 0, "received": getattr(u, "completion_tokens", 0) or 0}
    return resp.choices[0].message.content or "", usage


def describe_changes(model: str, issue: JiraIssue, diff: str, usage: dict | None = None) -> str | None:
    """LLM-written description, or None if the call fails or returns junk.

    If `usage` is given, it's filled with the call's token counts ({"sent", "received"}).
    """
    diff = diff.replace("\r", "")
    if len(diff) > MAX_DIFF_CHARS:
        diff = diff[:MAX_DIFF_CHARS] + "\n... (diff truncated)"
    prompt = PROMPT.format(
        key=issue.key,
        summary=issue.summary,
        description=issue.description or "(no description)",
        diff=diff,
    )
    try:
        text, call_usage = _complete(model, prompt)
        text = text.strip()
        if usage is not None:
            usage.update(call_usage)
    except Exception:
        log.exception("Could not generate PR description for %s", issue.key)
        return None
    text = re.sub(r"^```(?:markdown|md)?\s*\n(.*)\n```$", r"\1", text, flags=re.S).strip()
    return text if "## Summary" in text else None


def summary_line(description: str | None) -> str:
    """The text of the '## Summary' section, flattened to one paragraph."""
    if not description:
        return ""
    m = re.search(r"## Summary\s*\n(.*?)(?=\n## |\Z)", description, flags=re.S)
    return " ".join(m.group(1).split()) if m else ""


def build_pr_body(
    *, issue: JiraIssue, jira_url: str, description: str | None, diff_stat: str, agent_log: str, checks_md: str = ""
) -> str:
    ticket = f"[{issue.key}]({jira_url}): {issue.summary}"
    main = description or (
        f"## Summary\nAutomated fix for {ticket}.\n\n"
        "_An AI-written description could not be generated; see the diff and agent log below._"
    )
    return (
        f"{main}\n\n"
        + (f"{checks_md}\n\n" if checks_md else "")
        + f"---\n"
        f"**Jira:** {ticket}\n\n"
        f"**Files changed**\n```\n{diff_stat.strip()}\n```\n\n"
        f"<details><summary>Agent log (tail)</summary>\n\n```\n{agent_log[-3000:]}\n```\n</details>\n\n"
        "_Generated by the Jira coding agent. Please review carefully before merging._"
    )
